GraduationProject/Models/OurCollective.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GraduationProject.Models
{
    public class OurCollective :Base
    {
        [Required, MaxLength(150)]
        public string Title { get; set; }
        [Required, MaxLength(500)]
        public string Subtitle { get; set; }
        public string Image { get; set; }
        [NotMapped]
        public IFormFile ImageFile { get; set; }
    }
}

GraduationProject/ViewModels/OurCollectiveViewModel.cs
using GraduationProject.Models;
using System.Collections.Generic;

namespace GraduationProject.ViewModels
{
    public class OurCollectiveViewModel
    {
        public List<OurCollective> ourCollectives { get; set; }
    }
}

GraduationProject/Areas/Admin/Controllers/OurCollectivesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GraduationProject.DAL;
using GraduationProject.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using GraduationProject.Utils;
using Microsoft.AspNetCore.Authorization;

namespace GraduationProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OurCollectivesController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;


        public OurCollectivesController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        // GET: Admin/OurCollectives
        [Authorize(Roles = "Admin,SuperAdmin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.ourCollectives.ToListAsync());
        }

        // GET: Admin/OurCollectives/Details/5
        [Authorize(Roles = "Admin,SuperAdmin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ourCollective = await _context.ourCollectives
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ourCollective == null)
            {
                return NotFound();
            }

            return View(ourCollective);
        }

        // GET: Admin/OurCollectives/Create
        [Authorize(Roles = "Admin,SuperAdmin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/OurCollectives/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,SuperAdmin")]
        public async Task<IActionResult> Create([Bind("Title,ImageFile,Subtitle,Image,Id")] OurCollective ourCollective)
        {
            if (ModelState.IsValid)
            {
                if (!ourCollective.ImageFile.IsImage())
                {
                    ModelState.AddModelError("ImageFile", "File must be an image.");
                    return View();
                }
                if (!ourCollective.ImageFile.IsValidSize(5000))
                {
                    ModelState.AddModelError("ImageFile", "Max file size is 5000 kbs.");
                    return View();
                }
                ourCollective.Image = await ourCollective.ImageFile.Upload(_env.WebRootPath, @"assets\img\Upload");
                _context.Add(ourCollective);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ourCollective);
        }

        // GET: Admin/OurCollectives/Edit/5
        [Authorize(Roles = "Admin,SuperAdmin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ourCollective = await _context.ourCollectives.FindAsync(id);
            if (ourCollective == null)
            {
                return NotFound();
            }
            return View(ourCollective);
        }

        // POST: Admin/OurCollectives/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin,SuperAdmin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Title,ImageFile,Subtitle,Image,Id")] OurCollective ourCollective)
        {
            if (id != ourCollective.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (!ourCollective.ImageFile.IsImage())
                {
                    ModelState.AddModelError("ImageFile", "File must be an image.");
                    return View();
                }
                if (!ourCollective.ImageFile.IsValidSize(5000))
                {
                    ModelState.AddModelError("ImageFile", "Max file size is 5000 kbs.");
                    return View();
                }
                string filePath = Path.Combine(_env.WebRootPath, @"assets\img\Upload", ourCollective.Image);
                if (System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath);
                }
                ourCollective.Image = await ourCollective.ImageFile.Upload(_env.WebRootPath, @"assets\img\Upload");
                _context.Update(ourCollective);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ourCollective);
        }

        // GET: Admin/OurCollectives/Delete/5
        [Authorize(Roles = "Admin,SuperAdmin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ourCollective = await _context.ourCollectives
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ourCollective == null)
            {
                return NotFound();
            }

            return View(ourCollective);
        }

        // POST: Admin/OurCollectives/Delete/5
        [Authorize(Roles = "Admin,SuperAdmin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ourCollective = await _context.ourCollectives.FindAsync(id);
            string filePath = Path.Combine(_env.WebRootPath, @"assets\img\Upload", ourCollective.Image);
            if (System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
            }
            _context.ourCollectives.Remove(ourCollective);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OurCollectiveExists(int id)
        {
            return _context.ourCollectives.Any(e => e.Id == id);
        }
    }
}

GraduationProject/Controllers/OurCollectivesController.cs
using GraduationProject.DAL;
using GraduationProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace GraduationProject.Controllers
{
    public class OurCollectivesController : Controller
    {
        private readonly AppDbContext db;
        public OurCollectivesController(AppDbContext _db)
        {
            db = _db;
        }
        public async Task<IActionResult> Index()
        {
            OurCollectiveViewModel ocvm = new OurCollectiveViewModel()
            {
                ourCollectives = await db.ourCollectives.ToListAsync(),
            };
            return View(ocvm);
        }

        public async Task<IActionResult> Info(int? id)
        {
            if (id == null) return NotFound();

            var ourCollective = await db.ourCollectives
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ourCollective == null) return NotFound();
            return View(ourCollective);
        }
    }
}

GraduationProject/Views/OurCollectives/Index.cshtml
@model OurCollectiveViewModel

<section id="ourTeam">
    <div class="container-fulid ourTeamHeader">
        <h1>Komandalarimiz</h1>
    </div>
    <div class="container">
        <div class="row pt-5 my-3">
               @{ int location = 1;}
            @foreach (OurCollective ourCollective in @Model.ourCollectives)
            {
                location++;

                if (location % 2 == 1)
                {
                    <div class="ourTeamCard my-3 d-flex align-items-center justify-content-between">
                        <div class="col-7 ourcollectiveInfo" >
                            <h2>@ourCollective.Title</h2>
                            <p>
                                @ourCollective.Subtitle
                            </p>
                            <a  class="gold-button" asp-controller="OurCollectives" asp-action="Info" asp-route-id="@ourCollective.Id">Read more</a>
                        </div>
                        <div class="col-5">
                            <img src="~/assets/img/Upload/@ourCollective.Image" alt="">
                        </div>
                    </div>
                }
                else
                {
                    <div class="ourTeamCard my-3 d-flex align-items-center justify-content-between">
                        <div class="col-5">
                            <img src="~/assets/img/Upload/@ourCollective.Image" alt="">

                        </div>
                        <div class="col-7 ourcollectiveInfo">
                            <h2>@ourCollective.Title</h2>
                            <p>
                                @ourCollective.Subtitle
                            </p>
                            <a class="gold-button" asp-controller="OurCollectives" asp-action="Info" asp-route-id="@ourCollective.Id">Read more</a>

                        </div>
                    </div>
                }

            }
        </div>
    </div>
</section>

GraduationProject/Views/OurCollectives/Info.cshtml
@model GraduationProject.Models.OurCollective
<section id="InfoOurCollective">
        <div class="container">
            <div class="row">
                <img src="~/assets/img/Upload/@Model.Image" alt="">
                <h1>@Model.Title</h1>
                
                <p>
                    @Model.Subtitle
                </p>
            </div>
        </div>
    </section>